# ---------------------------------------------------------------
# Basic
# ---------------------------------------------------------------

# Appearance
appearance:
  accent_color: '#1eb4f0'
  foreground_color: '#363636'
  border_color: '#e0e0e0'
  background: '#f3f6f7'
  sidebar_background: '#607d8b linear-gradient(to bottom,#607d8b 0%,#26323b 100%)'
  card_background: '#fff'

  # All background settings above support image, e.g.,
  # '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa' or
  # 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # Maximum width of content
  content_width: 720

  # Fonts
  font:
    # Url of font css file
    # Below is a font set containing Baloo Bhaijaan, Josefin Sans, Montserrat and Inconsolata from Google Fonts.
    url: //cdn.jsdelivr.net/gh/PikaSama/shelter-images@1.4.3/static/css/font.css

    # Base font which applied to body
    base: "'Josefin Sans', 'PingFang SC', Microsoft YaHei"
    # Sidebar author font, fallback to `base`
    logo:
    # Sidebar menu font, fallback to `base`
    menu: 'Baloo Bhaijaan'
    # Font for:
    # - percentage on the fab button
    # - month text on archives page
    # - count
    # - pager
    # - toc index
    # - category pill
    # fallback to `base`
    label: Montserrat
    # Headline(h1, h2, h3, h4, h5, h6) font, fallback to `base`
    heading:
    # Code and code block
    code: Inconsolata, monospace
    # Base font for printing which applied to body
    print:
    
  # onedark
  highlight: [
      '#282c34', '#353b45', '#3e4451', '#545862',
      '#565c64', '#abb2bf', '#b6bdca', '#c8ccd4',
      '#e06c75', '#d19a66', '#e5c07b', '#98c379',
      '#56b6c2', '#61afef', '#c678dd', '#be5046'
  ]
  # ir black
  # highlight: [
  #     '#000000', '#242422', '#484844', '#6c6c66',
  #     '#918f88', '#b5b3aa', '#d9d7cc', '#fdfbee',
  #     '#ff6c60', '#e9c062', '#ffffb6', '#a8ff60',
  #     '#c6c5fe', '#96cbfe', '#ff73fd', '#b18a3d'
  # ]

  # Default Light by Chris Kempson (http://chriskempson.com)
  # highlight: [
  #  '#f8f8f8', '#e8e8e8', '#d8d8d8', '#b8b8b8',
  #  '#585858', '#383838', '#282828', '#181818',
  #  '#ab4642', '#dc9656', '#f7ca88', '#a1b56c',
  #  '#86c1b9', '#7cafc2', '#ba8baf', '#a16946'
  # ]

  # Harmonic16 Light by Jannik Siebert (https://github.com/janniks)
  # highlight: [
  #   '#f7f9fb', '#e5ebf1', '#cbd6e2', '#aabcce',
  #   '#627e99', '#405c79', '#223b54', '#0b1c2c',
  #   '#bf8b56', '#bfbf56', '#8bbf56', '#56bf8b',
  #   '#568bbf', '#8b56bf', '#bf568b', '#bf5656'
  # ]

  # Tomorrow Night by Chris Kempson (http://chriskempson.com)
  # highlight: [
  #   '#1d1f21', '#282a2e', '#373b41', '#969896',
  #   '#b4b7b4', '#c5c8c6', '#e0e0e0', '#ffffff',
  #   '#cc6666', '#de935f', '#f0c674', '#b5bd68',
  #   '#8abeb7', '#81a2be', '#b294bb', '#a3685a'
  # ]

# Sidebar profile
profile:
  # `email` is used for gravatar(https://en.gravatar.com),
  # fallback to `hexo.config.email` if not specified
  # email:

  # You can set Avatar URL directly
  avatar: //cdn.jsdelivr.net/gh/PikaSama/shelter-images@1.4.3/images/avatar2.png

  bio: ""
# Sidebar navigation links
menu:
  ğŸ  Home: /
  ğŸ“” About: /about
  â“ Help: /help
  âš™ï¸ Settings: /settings

# Social media URL
# Try to sort by changing the order of the keys
sns:
  # `email` will fallback to `profile.email` if not specified
  email: pikasama@qq.com
  # If you use hexo-generator-feed, `sns.feed` can be left blank
  # and the theme will try to get `hexo.config.feed.path`.
  feed:
  github: https://github.com/pikasama
  twitter:
  facebook:
  instagram:
  tumblr:
  dribbble:
  telegram:
  youtube:
  hangouts:
  linkedin:
  pinterest:
  soundcloud:
  myspace:
  weibo:
  qq: //wpa.qq.com/msgrd?v=3&uin=2108586824&site=qq&menu=yes

# Sidebar footer copyright info
footer:
  # Set to false to hide.
  copyright: '<span style="font-size:110%;">&copy; 2020 ğŸ’– <a href="https://zorin.beaa.cn">Zorin</a></span>'

  # Set to false to hide Hexo link.
  powered: false

  # Set to false to hide theme link.
  theme: false

  # Custom text.
  custom: <span style="font-size:120%;" id="busuanzi_container_site_pv">PV:<span id="busuanzi_value_site_pv"></span> | </span><span style="font-size:120%;" id="busuanzi_container_site_uv">UV:<span id="busuanzi_value_site_uv"></span></span><br /><span style="font-size:120%;">æœ¬ç«™ç”±<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral" target="_blank"><img src="https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@1.4.3/images/upyun.png" height="24" width="48" alt="upyun"></img></a>æä¾›CDNåŠ é€ŸæœåŠ¡</span><br /><a href="http://www.beian.miit.gov.cn/" style="font-size:110%;">è±«ICPå¤‡18001626å·</a>
  #   href="https://pages.github.com/"><b>Github Pages</b></a>


# ---------------------------------------------------------------
# Content
# ---------------------------------------------------------------

# Page
page:
  toc: true
  reward: true
  copyright: true


# Post
post:
  per_page: 7
  toc: true
  reward: true
  copyright: true

# Archive
archive:
  per_page: 7

# Tag
tag:
  per_page: 8

# Category
category:
  per_page: 8

# Search
search:
  fab: true
  page: true

  adapter:
    range:
      - post
      - page

    limit: 10000
    per_page: 7

# ---------------------------------------------------------------
# Content addons
# ---------------------------------------------------------------

# Prefix/Suffix of image URL, useful for CDN, for example,
# `![cat](images/cat.gif)` will convert to
# <img src="https://cdn.example.com/images/cat.gif?m=webp&q=80" alt="cat">
assets:
  prefix: 'https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@latest'
  # suffix: '?m=webp&q=80'

# Table of content, enabled by default, set to `false` to disable.
toc:
  # The depth of toc, default to `3`, maximum to `4`.
  depth: 4

  # Showing index before title, eg. 1.1 title, default to `true`
  index: false

# Reward
reward:
  text: Buy me a can of Vita lemon tea.ğŸ¹
  methods:
    - name: alipay
      qrcode: https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@latest/images/alipay.jpg
      url: https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@latest/images/alipay.jpg
      text: æ”¯ä»˜å®èµåŠ©äºŒç»´ç ~
      color: '#00bfff'
    - name: wechat
      qrcode: https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@latest/images/wechat.png
      url: https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@latest/images/wechat.png
      text: å¾®ä¿¡èµåŠ©äºŒç»´ç ~
      color: '#00ff7f'
# Copyright notice
# It is possible to use front matter `copyright` to override this setting.
copyright:
  author: true
  link: true
  license: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="nofollow" target="_blank">ç½²å-éå•†ä¸šæ€§-å…±äº«æ–¹å¼ä¸€è‡´</a>(CC BY-NC-SA 4.0)<br />åšå®¢é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨æ­¤åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜æ¥æºï¼

comments:
  # disqus:
  #   shortname: disqus_shortname
  #   # Or you can set disqus script URL directly
  #   script: //disqus_shortname.disqus.com/embed.js
  #   # Autoload, default to `true`, set to `false` to display a button
  #   autoload: false

  # livere:
  #   uid: livere_uid
  #   # LiveRe script, default to `https://cdn-city.livere.com/js/embed.dist.js`
  #   script:
  #   # Autoload, default to `true`, set to `false` to display a button
  #   autoload: false


# ---------------------------------------------------------------
# Misc
# ---------------------------------------------------------------

# URL prefix for theme statics
static_prefix:

# URL prefix for json data
# If your json file is put in a cdn server,
# set data_prefix as '//cdn.com/path/to/path/your_json_dir' and data_dir as 'your_json_dir'
data_prefix:

# Folder where json file will be generated to, default to 'api'
data_dir:

# Favicon, default to `favicon.ico`
favicon:  https://cdn.jsdelivr.net/gh/PikaSama/shelter-images@1.4.3/images/icon.png

# Google analytics
# ga: UA-00000000-0

# SEO
seo:
  # Render structured-data in <head>, default to `false`
  # structured_data: true
  # Server-side rendering (SSR), default to `false`
  # ssr: true

# PWA
pwa:
  # Workbox (https://developers.google.com/web/tools/workbox/) is a JavaScript
  # libraries for adding offline support to web apps,
  # disabled by default, remove the hash to enable
  # workbox:
  #   # Workbox cdn, uses google by default, below is an example of using alicdn
  #   cdn: https://g.alicdn.com/kg/workbox/3.3.0/workbox-sw.js
  #   module_path_prefix: https://g.alicdn.com/kg/workbox/3.3.0/
  #   # Expire time in hour, 4 by default, set to 0 to be permanent,
  #   # caches will be forcibly deleted the next time the site is updated.
  #   expire: 4
  #   # The worker script name, `sw.js` by default
  #   name: sw.js
  #   # Custom rules
  #   rules:
  #     - name: jsdelivr
  #       strategy: staleWhileRevalidate
  #       regex: https://cdn\\.jsdelivr\\.net
  #     - name: gtm
  #       strategy: staleWhileRevalidate
  #       regex: https://www\\.googletagmanager\\.com\?id=.*
  #     - name: gravatar
  #       strategy: staleWhileRevalidate
  #       regex: https://www\\.gravatar\\.com
  #     - name: theme
  #       strategy: staleWhileRevalidate
  #       regex: /.*\\.(?:js|css|woff2|png|jpg|gif)$
  #     - name: cdn
  #       strategy: staleWhileRevalidate
  #       regex: https://cdn\\.yourdomain\\.com
  #     - name: json
  #       strategy: cacheFirst
  #       regex: your_data_prefix/.*\\.json

  # manifest.json
  # manifest:
  #   short_name:
  #   name:
  #   start_url: /
  #   theme_color: '#2a2b33'
  #   background_color: '#2a2b33'
  #   icons:
  #     - src: icon-194x194.png
  #       sizes: 194x194 512x512
  #       type: image/png
  #     - src: icon-144x144.png
  #       sizes: 144x144
  #       type: image/png
plugins:
# js
  - //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - //cdn.jsdelivr.net/npm/minivaline@4/dist/MiniValine.min.js
  - //cdn.jsdelivr.net/npm/typed.js@2.0.11/lib/typed.min.js
  - //cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - //cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  - //cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js
  - //zorin.beaa.cn/test/modernizr.custom.js
  - //zorin.beaa.cn/test/classie.js
  - //zorin.beaa.cn/test/notificationFx.js
  - //zorin.beaa.cn/test/theme.js
  # custom
  - //zorin.beaa.cn/test/scriptLoader.js
  - //zorin.beaa.cn/test/themes.js
# css
  - //cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css
  - //cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  - //cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css
  - //zorin.beaa.cn/test/clipboard.css
  - //zorin.beaa.cn/test/ns-default.css
  - position: sidebar
    template: |
      <is-palette2></is-palette2>
  - position: comments
    template: |
      <script src="//zorin.beaa.cn/test/cfg-Minivaline.js"></script>
  - position:
      - page
    template: |
      <script src="//zorin.beaa.cn/test/scriptLoader-page.js"></script>
  - position:
      - post
    template: |
      <script src="//zorin.beaa.cn/test/scriptLoader-post.js"></script>